### ISSUE TITLE
Type TraceableSqlCommand not available when upgrading nuget package 2.7.3 to 2.8.0

### ISSUE THREAD

**Issue by tcpmod** [aws/aws-xray-sdk-dotnet#261]
When updating the nuget package Amazon.XRay.Recorder.Handlers.SqlServer package version 2.7.3 to 2.8.0 the class TraceableSqlCommand is no longer available.

Scenario: .net6 console app

Running dotnet build gives the error

```
error CS0246: The
type or namespace name 'TraceableSqlCommand' could not be found (are you missing a using directive or an assembly refer
ence?
```

I've tried this on both my existing .net 6 project and a clean console app in .net 6

When I downgrade back to 2.7.3 TraceableSqlCommand is recognised and the solution builds as it previously did.

**Comment by tcpmod** [comment]
Thanks for confirming @jon-armen - yes I couldn't see any obvious reason why it wasn't there. cheers.

**Comment by srprash** [comment]
Hi @tcpmod 
Sorry for the miss on our end. We will get a new release out soon.

@jon-armen Thanks for addressing the issue so promptly. :)

**Comment by srprash** [comment]
@tcpmod The issue has now been fixed in the patch release v2.11.1.
Pleas verify it works and feel free to reopen this issue if it still doesn't work. Thanks!
